### PR TITLE
Update HEAD subnets to all linux machines in nodeinfo

### PR DESCRIPTION
**Pull request by taldcroft**
## Description

For the promotion of kadi commands v2, we want the production use of starcheck for load review to only use the `flight` scenario. In https://github.com/sot/starcheck/pull/391 this is implemented by checking if the host machine is on the HEAD network using the `on_head_network()` function here.

The list of subnets that was being included as being "on HEAD" was incomplete, and in particular at least one machine SOT MP uses for running load review was not in the list.

This PR uses the `nodeinfo` command on HEAD to get a full list of IP addresses, filters down to linux machines, and then extracts the complete set of subnets below 131.142. It includes a utility script that can be used in the future to maintain the list.

## Interface impacts

None

### Unit tests

- [x] No unit tests

### Functional tests

- Ran `on_head_network()` on Mac, got `False`
- Ran on `kady` and `baffin` and got `True`

### CODE REVIEW

**Comment by jeanconn** [comment]
I'll look at this in more detail, but I think this will do kinda the wrong thing for machines like jiffy on the self-managed subnet that can't see HEAD /proj/sot/ska.  What are we assuming implicitly by passing the on_head_network test?  I mean, it is fine if I shouldn't run some ska_testr tests on jiffy (because they will try for resources they can't reach) ...

For some of our applications, maybe should explicitly check "is this a linux machine that can see /proj/sot/ska served from numa".  For starcheck, I still like the idea of printing something that it was run in a non-flight scenario if it was run in a non-flight scenario.

**Comment by taldcroft** [comment]
Good catch, urgh. What about adding an additional criterion that `/proj/sot/ska` is visible?

I have implemented the "printing something" bit in starcheck.

**Comment by jeanconn** [comment]
I suppose if you are on this set of IP address *and* can see /proj/sot/ska, that would be simple and make sense.  I can't think of a machine that would be on the list and have access for which it would be the *wrong* thing.  And if somebody set up their self-managed machine to have a /proj/sot/ska... well that's a special kind of user.

**Comment by taldcroft** [comment]
@jeanconn - see [cb8f295](https://github.com/sot/testr/pull/45/commits/cb8f295cb76d6250f4e14883be31a05eaef84334).

I retested on my machine and on kady and baffin with the expected results.

**Comment by taldcroft** [comment]
@jeanconn - if you are OK with this approach can you approve the PR?

**Review by jeanconn — APPROVED** [review]

**Pull request merged**
