### PR TITLE
Run pytest from TESTR_OUTPUT_DIR

### PR DESCRIPTION
**Pull request by taldcroft**
## Description

This is a solution to the `hypothesis` problem (see `#aspect-team "falling back to an in-memory database for this session" hypothesis` ).

This would also generally solve the problem of tests that accidentally write stuff into package directories (with understanding that tests really should not do that).

## Interface impact

When running `ska_testr` or something like `import Chandra.Maneuver; Chandra.Maneuver.test()`, the path to the test file will be a long one, going from the current working directory up to root (with `../../  etc`) and then back down through the Python distribution files. See the functional testing example.

## Testing

- [n/a] No unit tests
- [x] Functional testing

### Functional test

This was tested in my existing `ska3-next` environment (2022.2rc6) so that I could hack it just slightly. In this case I created a directory `$CONDA_PREFIX/lib/python3.8/site-packages/.hypothesis` which is not writeable by anyone. This was to check if the fix worked since the offending `.hypothesis` directory gets deleted by pytest/hypothesis after tests complete. Using the unpatched (flight) version of `testr` I confirmed that this hack reproduced the problem we have seen on HEAD linux.

#### Testing from ska_testr
```
(ska3-next) ➜  ska_testr git:(master) export PYTHONPATH=$HOME/git/testr
(ska3-next) ➜  ska_testr git:(master) cd ~/git/ska_testr
(ska3-next) ➜  ska_testr git:(master) python -m testr.packages --include Chandra.Maneuver
****************************************
*** package Chandra.Maneuver         ***
****************************************

Copying input tests /Users/aldcroft/git/ska_testr/packages/Chandra.Maneuver to output dir /Users/aldcroft/git/ska_testr/outputs/logs/Darwin_2022-03-10T13-49-09_2022.2rc6-2aa4956_mprovost-l1.occ.harvard.edu/Chandra.Maneuver
Running python test_unit.py script
Bash-08:49:09> export TESTR_FILE='test_unit.py'
Bash-08:49:09> export TESTR_STATUS='not run'
Bash-08:49:09> export TESTR_INTERPRETER='python'
Bash-08:49:09> export TESTR_OUT_DIR='/Users/aldcroft/git/ska_testr/outputs/logs/Darwin_2022-03-10T13-49-09_2022.2rc6-2aa4956_mprovost-l1.occ.harvard.edu/Chandra.Maneuver'
Bash-08:49:09> export TESTR_REGRESS_DIR='/Users/aldcroft/git/ska_testr/outputs/regress/Darwin_2022-03-10T13-49-09_2022.2rc6-2aa4956_mprovost-l1.occ.harvard.edu/Chandra.Maneuver'
Bash-08:49:09> export TESTR_PACKAGES_REPO='https://github.com/sot'
Bash-08:49:09> export TESTR_PACKAGE='Chandra.Maneuver'
Bash-08:49:09> export TESTR_PACKAGE_VERSION='3.8.0'
Bash-08:49:09> python test_unit.py
HO

 /Users/aldcroft/git/ska_testr/outputs/logs/Darwin_2022-03-10T13-49-09_2022.2rc6-2aa4956_mprovost-l1.occ.harvard.edu/Chandra.Maneuver 


============================= test session starts ==============================
platform darwin -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /Users/aldcroft/miniconda3/envs/ska3-next/bin/python
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/aldcroft/git/ska_testr/outputs/logs/Darwin_2022-03-10T13-49-09_2022.2rc6-2aa4956_mprovost-l1.occ.harvard.edu/Chandra.Maneuver/.hypothesis/examples')
rootdir: /Users/aldcroft
plugins: remotedata-0.3.3, doctestplus-0.11.2, arraydiff-0.3, anyio-2.2.0, hypothesis-6.29.3, mock-3.6.1, filter-subpackage-0.1.1, openfiles-0.5.0, astropy-header-0.1.2, cov-3.0.0
collected 4 items                                                              

../../../../../../miniconda3/envs/ska3-next/lib/python3.8/site-packages/Chandra/Maneuver/tests/test_maneuver.py::test_attitudes PASSED
../../../../../../miniconda3/envs/ska3-next/lib/python3.8/site-packages/Chandra/Maneuver/tests/test_maneuver.py::test_versus_telemetry PASSED
../../../../../../miniconda3/envs/ska3-next/lib/python3.8/site-packages/Chandra/Maneuver/tests/test_maneuver.py::test_inject_errors PASSED
../../../../../../miniconda3/envs/ska3-next/lib/python3.8/site-packages/Chandra/Maneuver/tests/test_maneuver.py::test_inject_array_errors PASSED

- generated xml file: /Users/aldcroft/git/ska_testr/outputs/logs/Darwin_2022-03-10T13-49-09_2022.2rc6-2aa4956_mprovost-l1.occ.harvard.edu/Chandra.Maneuver/test_unit.py.xml -
============================== 4 passed in 0.89s ===============================
Bash-08:49:11> 
Running python post_check_logs.py script
Bash-08:49:11> export TESTR_FILE='post_check_logs.py'
Bash-08:49:11> export TESTR_STATUS='not run'
Bash-08:49:11> export TESTR_INTERPRETER='python'
Bash-08:49:11> export TESTR_OUT_DIR='/Users/aldcroft/git/ska_testr/outputs/logs/Darwin_2022-03-10T13-49-09_2022.2rc6-2aa4956_mprovost-l1.occ.harvard.edu/Chandra.Maneuver'
Bash-08:49:11> export TESTR_REGRESS_DIR='/Users/aldcroft/git/ska_testr/outputs/regress/Darwin_2022-03-10T13-49-09_2022.2rc6-2aa4956_mprovost-l1.occ.harvard.edu/Chandra.Maneuver'
Bash-08:49:11> export TESTR_PACKAGES_REPO='https://github.com/sot'
Bash-08:49:11> export TESTR_PACKAGE='Chandra.Maneuver'
Bash-08:49:11> export TESTR_PACKAGE_VERSION='3.8.0'
Bash-08:49:11> python post_check_logs.py
Bash-08:49:12> 
****************************************
*** Chandra.Maneuver Test Summary    ***
*** test_unit.py         pass        ***
*** post_check_logs.py   pass        ***
****************************************
...
```
#### Testing from the imported package 
```
(ska3-next) ➜  testr git:(test-from-current-dir) cd ~
(ska3-next) ➜  ~ ipython
Python 3.8.12 (default, Oct 12 2021, 06:23:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import Chandra.Maneuver

In [2]: Chandra.Maneuver.test('-v')
================================================================== test session starts ==================================================================
platform darwin -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /Users/aldcroft/miniconda3/envs/ska3-next/bin/python
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/aldcroft/.hypothesis/examples')
rootdir: /Users/aldcroft
plugins: remotedata-0.3.3, doctestplus-0.11.2, arraydiff-0.3, anyio-2.2.0, hypothesis-6.29.3, mock-3.6.1, filter-subpackage-0.1.1, openfiles-0.5.0, astropy-header-0.1.2, cov-3.0.0
collected 4 items                                                                                                                                       

miniconda3/envs/ska3-next/lib/python3.8/site-packages/Chandra/Maneuver/tests/test_maneuver.py::test_attitudes PASSED                              [ 25%]
miniconda3/envs/ska3-next/lib/python3.8/site-packages/Chandra/Maneuver/tests/test_maneuver.py::test_versus_telemetry PASSED                       [ 50%]
miniconda3/envs/ska3-next/lib/python3.8/site-packages/Chandra/Maneuver/tests/test_maneuver.py::test_inject_errors PASSED                          [ 75%]
miniconda3/envs/ska3-next/lib/python3.8/site-packages/Chandra/Maneuver/tests/test_maneuver.py::test_inject_array_errors PASSED                    [100%]

=================================================================== 4 passed in 0.71s ===================================================================

```
#### Testing from git repo using `python setup.py test`
```
(ska3-next) ➜  ~ cd ~/git/Chandra.Maneuver
(ska3-next) ➜  Chandra.Maneuver git:(master) 
(ska3-next) ➜  Chandra.Maneuver git:(master) python setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing Chandra.Maneuver.egg-info/PKG-INFO
writing dependency_links to Chandra.Maneuver.egg-info/dependency_links.txt
writing requirements to Chandra.Maneuver.egg-info/requires.txt
writing top-level names to Chandra.Maneuver.egg-info/top_level.txt
package init file 'Chandra/__init__.py' not found (or not a regular file)
adding license file 'LICENSE.rst'
writing manifest file 'Chandra.Maneuver.egg-info/SOURCES.txt'
running build_ext
================================================================== test session starts ==================================================================
platform darwin -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /Users/aldcroft/git/Chandra.Maneuver, configfile: pytest.ini
plugins: remotedata-0.3.3, doctestplus-0.11.2, arraydiff-0.3, anyio-2.2.0, hypothesis-6.29.3, mock-3.6.1, filter-subpackage-0.1.1, openfiles-0.5.0, astropy-header-0.1.2, cov-3.0.0
collected 4 items                                                                                                                                       

Chandra/Maneuver/tests/test_maneuver.py ....                                                                                                      [100%]

=================================================================== warnings summary ====================================================================
../../miniconda3/envs/ska3-next/lib/python3.8/site-packages/setuptools_scm/__init__.py:69
  /Users/aldcroft/miniconda3/envs/ska3-next/lib/python3.8/site-packages/setuptools_scm/__init__.py:69: DeprecationWarning: parse function setuptools_scm_git_archive.parse are required to provide a named argument 'config', setuptools_scm>=8.0 will remove support.
    version = _call_entrypoint_fn(root, config, ep.load())

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================================================= 4 passed, 1 warning in 0.92s ==============================================================
```

### CODE REVIEW

**Comment by jeanconn** [comment]
@javierggt what are your thoughts on this in principle?  This at least seems a more contained solution than the others.  For example my conftest.py solution would apparently require adding a conftest.py to disable hypothesis testing for each of our modules.  Another approach I suppose could be to patch pytest itself but that seems messy.

**Comment by javierggt** [comment]
If this causes files to be created in the current working directory, It might be better to run it from the output dir (given by the option `--outputs-dir`). That way all the garbage can be easily identified.

**Comment by javierggt** [comment]
For the record: my previous changes to testr were explicitly to remove the constraint that it had to be run from the ska_testr directory.

**Comment by javierggt** [comment]
The output directory is passed to the runner via the TESTR_OUT_DIR environmental variable, so perhaps chdir to that directory.

**Comment by jeanconn** [comment]
We could alternatively add the lines to ignore the warning for every package.  I'm not sure which is more work.

**Comment by taldcroft** [comment]
@javierggt - I like the idea of changing to the `TESTR_OUT_DIR`. As long as having those new long values for the test name is OK with you then let's do it. I'm thinking about the skare3 package dashboard, not sure how that works.

**Comment by javierggt** [comment]
ah, I had not understood the point with the long test names. What I might care about is the json output. I will have to test and presumably parse the test name.

**Comment by taldcroft** [comment]
I'm feeling more enthusiastic about this solution and I cleaned up the title and description. 

If necessary it seems like you can do a regex to find `lib/python3.8/site-packages` (allowing for variations in the `3.8`) and use that as the starting point.

**Comment by javierggt** [comment]
I ran the following command, which is a simplified version of what testr runs:

```
pytest $SKA/lib/python3.8/site-packages/Chandra/Maneuver -v -s -Wignore:" 'soft_unicode' has been renamed to 'soft_str'" --junit-xml=test_unit.py.xml -o junit_family=xunit2 -p no:cacheprovider
```

and the xml output is this, which does not have the long names:

```
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
  <testsuite name="pytest" errors="0" failures="0" skipped="0"
             tests="4" time="15.483"
             timestamp="2022-03-10T10:03:38.602171"
	     hostname="kady.cfa.harvard.edu">
    <testcase classname="tests.test_maneuver" name="test_attitudes"
              time="0.006" />
    <testcase classname="tests.test_maneuver"
              name="test_versus_telemetry" time="2.313" />
    <testcase classname="tests.test_maneuver"
              name="test_inject_errors" time="0.012" />
    <testcase classname="tests.test_maneuver"
	      name="test_inject_array_errors" time="0.026" />
  </testsuite>
</testsuites>
```

I think it will be OK, but I still have to check something.

**Comment by taldcroft** [comment]
Going to disable the plugin with `-p no:hypothesispytest` instead.

**Comment by taldcroft** [comment]
BTW, I just saw this in the code, which makes me wonder again about going back to the solutino in this PR:
```
    # Disable caching of test results to prevent users trying to write into
    # flight directory if tests fail running on installed package.
    args = args + ('-p', 'no:cacheprovider')
```

**Pull request closed without merging**
