### PR TITLE
Add duplicate_package_info function

### PR DESCRIPTION
**Pull request by taldcroft**
## Description

Provide a new helper function for use in `setup.py` to facilitate flattening namespace packages, e.g. https://github.com/sot/Ska.Sun/pull/22.

## Interface impacts

Adds a function.

### Unit tests

- [x] No unit tests

### Functional tests

Used in https://github.com/sot/Ska.Sun/pull/22 to generate a working package. It seems to work.

### CODE REVIEW

**Comment by javierggt** [comment]
Why is this in testr? I still do not get it?

I would think this is the thing to put in ska_helpers.

**Comment by taldcroft** [comment]
This new function is here purely because of the historical location of `setup_helper.py` within `testr`. I'm open to suggestions for a better home.

**Comment by jeanconn** [comment]
From a dependency perspective, we generally require testr and ska_helpers for all the conda packages so there's no difference on that side.

**Comment by jeanconn** [comment]
@javierggt were you thinking in a new `ska_helpers.setup_helpers` or some such?  If we're going to move it I'd like to do that before testing and reviewing the other packages that depend on the new function.

**Comment by javierggt** [comment]
So then we can put things into whatever module we want? Because we install all of them always anyway.

Ska_helpers started as a package for **exactly** this kind of functions (to help manage ska packages), and the version was the first addition to it. Now it has other things that are not for package management (like logging, lazy loading), and this one is not there, so now ska_helpers is whatever anyway.

I am not going to stop merging this if you think it is fine. Just saying...

**Comment by jeanconn** [comment]
Regarding "Because we install all of them always anyway." I was specifically talking about the conda dependencies where both of those packages (testr, ska_helpers) were now required basically by every other package.  But I agree with you that ska_helpers seems really a better fit.

**Comment by javierggt** [comment]
ah, somehow I missed the comment you made right before I posted my last comment. Yes, something like setup_helpers could be.

**Comment by jeanconn** [comment]
OK.  I tossed it in there at https://github.com/sot/ska_helpers/pull/26 .  Does that work for both of you?

**Comment by taldcroft** [comment]
Closed in favor of https://github.com/sot/ska_helpers/pull/26 .

**Pull request closed without merging**
